name: screen_brightness_monitor
description: "A Flutter plugin to monitor screen brightness changes on Android and iOS using JNI and FFI."
version: 1.0.0
homepage: https://github.com/orestesgaolin/screen_brightness_monitor
issue_tracker: https://github.com/orestesgaolin/screen_brightness_monitor/issues
topics:
  - screen
  - brightness
  - jnigen
  - swiftgen
  - ffi

environment:
  sdk: ^3.11.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3
  jni: ^0.15.2
  objective_c: ^9.3.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  jnigen: ^0.15.0
  swiftgen: ^0.1.2
  logging: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
